### ISSUE TITLE
Missing cert

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#116]
The `deregkey` cert is missing from `DCert`.

**Comment by Soupstraw** [comment]
We have a `regdrep` cert, but we're missing the `ccdereghot` cert

**Comment by WhatisRT** [comment]
Sorry, I meant `deregkey`, I fixed it at the top. We don't need `ccdereghot`, since that's covered by passing a `nothing` into `ccreghot`.

**Comment by WhatisRT** [comment]
This is done, the cert is called `dereg`.
