### ISSUE TITLE
Only allow proposals that have a path to be enacted

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#236]
The hash protection scheme means we can only enact actions that were designed to be applied on top of the current one. We now want to additionally guarantee that all current proposals have a sequence of enactments that will get them enacted. This is what we need to do:
- [x] Add `allEnactable` predicate and its decision procedure.
- [x] Check that new proposals point to an existing proposal or the current state.
- [ ] Remove proposals that become impossible to enact at the epoch boundary.
- [ ] Prove that 'all proposals point at some previous proposal or the current state' is an invariant.

**Comment by williamdemeo** [comment]
@WhatisRT I have completed the first two tasks.  I have questions about the other two.
