### ISSUE TITLE
Remaining modeling questions for the axiomatic set theory

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#24]
There are some questions remaining about the modeling of the axiomatic set theory:

1. Can we make things level-polymorphic (probably) and if so, is there a good way of allowing the model given by `Set A = A → Type`? The issue here is that `Set` is of type `Type a → Type (max a 1)`, so only if `a ≠ 0` it preserves the type. Allowing this would break some other stuff, for example the `unions` axiom.

2. The current `SpecProperty` situation is a bit messy. It might be worth replacing this by a simple sum type, where we allow either all properties or all decidable properties in the `specification` axiom. This would technically be less general, but I'm not aware of any situation where it wouldn't be one of those two. This would probably simplify things, but it might also not, we just have to try it.

3. Do we need a dependent version of the `replacement` axiom? This has come up twice now, and may be useful.

**Comment by williamdemeo** [comment]
I'll start working on this.  (I've been wondering how far we could get with `Set A = A -> Type` (which is essentially `Pred A`).)

**Comment by williamdemeo** [comment]
I'll make a PR called `types-not-sets` with the following goals.

- [ ] substitute `Pred A 0` for `Set A`
- [ ] rename `Set` to `Type` when using it to denote type (not set)

**Comment by WhatisRT** [comment]
Just to be sure, your plan is to make something akin to `List-Model` in `Axiom.Set.List`, correct? Note that this won't admit instances of `Theoryᶠ` and `Theoryᵈ`, which are both necessary for the ledger model. So while this is certainly nice to have, it won't actually do anything useful.

I'm a bit hesitant to rename `Set` to `Type` globally. I agree that Agda should have called it `Type` in the first place, but most people in the Agda community use `Set` and I'd rather not diverge. At some point I'd like to move the set theory into its own library and it makes sense that that library would deviate from convention, but I'm not sure the rest of the ledger should.

**Comment by WhatisRT** [comment]
Closing this in favour of https://github.com/input-output-hk/agda-sets/issues/1, https://github.com/input-output-hk/agda-sets/issues/2 and https://github.com/input-output-hk/agda-sets/issues/3 (apparently I cannot transfer this issue)
