### ISSUE TITLE
Explain/remove concepts/notations

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#282]
## Unavoidable (Do later)

Things that we can either not avoid for technical reasons or because they would make things massively more difficult. These need to be explained.

- [x] `record` definitions, `record` syntax for (de)constructing values
- [ ] #444

## Potentially avoidable (Do later)

Things that can be avoided/hidden at some cost. That cost needs to be weighed against the cost of adding an explanation (which also makes the document less accessible).

- [x] `open` for records
- [x] implicit arguments
- [x] `Σ`
- [x] `data`
- [x] `λ where` syntax
- [x]  Copatterns

## Should be avoided (Do soon)

These are things which aren't too difficult to avoid, are completely custom or only used in an FP context. Those need to have a very good reason to pay the cost of adding an explanation/increasing the barrier to entry.

- [x] `module` syntax
- [x] `_≗_` (fig 5)
- [x] ~`_⟪$⟫_` (fig 25)~ (afaik, this no longer appears in fig 25)
- [x] `_<$>_` (fig 25)
- [x] `sp-∘`
- [x] `to-sp`
- [x] `uncurry`
- [x] `foldr`

## Need explanations/cleanup (Do soon)

Things that definitely we want to use but still should have a (potentially very short) explanation. Some things in here may also be improved by being renamed. Some renames may require type classes or other mechanisms.

Name is probably good:
- [x] `_⊎_`
- [x] `_∷ʳ_`
- [x] `_⁻¹`
- [x] `_∣_`

May benefit from a rename:
- [ ] `_↾_`
- [ ] `_↾'_`
- [x] `_⊖_`
- [x] `_∘₂_`

Needs rename:
- [x] `Σᵐᵛ` -> `∑`, maybe `∑ᵛ`?
- [x] ~`mapˢ` - since we now have a `Functor` class, we can make an
      instance and write `map` instead~ (this is difficult, see #322)
- [x] `∅ᵐ` -> `∅`
- [x] `❴_❵ᵐ` -> `❴_❵`
- [x] `ℚ.0ℚ` -> `0ℚ` (`0ℚ` -> `0` via literal overloading later)
- [x] `_ℚ.≥_` -> `_≥_` or `_≤_`
- [x] `filterᵐ` -> `filter` (or maybe something else?)
- [x] `sucᵉ` -> `... + 1`
- [ ] #446

**Comment by WhatisRT** [comment]
For now, we should focus on putting out the biggest fires. This is anything in the **Should be avoided** and **Needs rename** sections.

**Comment by williamdemeo** [comment]
@WhatisRT Thank you for reorganizing this issue and making the priorities clear. 🚀 👍🏼

**Comment by williamdemeo** [comment]
@WhatisRT why do you want to be forced to use parentheses around `A ⇀ B`?  I thought one nice feature of our `⇀` symbol was that we *didn't* need parens.

**Comment by omelkonian** [comment]
> @WhatisRT why do you want to be forced to use parentheses around `A ⇀ B`? I thought one nice feature of our `⇀` symbol was that we _didn't_ need parens.

I remember adding such parentheses in my first cleanup PR; it is very easy to confuse it with the normal function space (esp. in some fonts where they are almost identical) and I also recall the fixity to be very brittle (you don't know if you want a map from functions or an input map...). To sum up, yes please always use parantheses when a map is part of a larger (function-with-arguments) type.

**Comment by WhatisRT** [comment]
Closing in favour of #444, #446 and #447.
