### ISSUE TITLE
Various cleanup items for the Conway spec

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#288]
This issue is for things that are necessary specifically for the Conway spec and don't fit elsewhere.

- [x] ~Fig. 8~ Fig. 13 (Protocol parameter declarations)
      Can we move `Acnt` elsewhere?
- [x] ~Fig. 14~ Fig. 12 has a lot of rules that don't have any
      preconditions. Explain that not all rules have a horizontal line
      and preconditions (or just make one so it looks consistent).
- [x] ~Fig. 15~ Fig. 13 - format
- [x] ~Fig. 17~ Fig. 15 - rules would be easier to read if all the `let`
      statements are above the line
- [ ] ~Fig. 40~ Fig. 43 (EPOCH transition system)
      The module shenanigans and record updates make this one
      especially hard to read

**Comment by williamdemeo** [comment]
Please correct me if I'm wrong, but I believe Fig 14 is now Fig 12 ("ENACT transition system")  (There are no horizontal lines or rules in Fig 14.)

**Comment by williamdemeo** [comment]
I think other Fig numbers might be wrong, too.

**Comment by williamdemeo** [comment]
@WhatisRT do you have any ideas re. where we might move `Acnt`?

**Comment by WhatisRT** [comment]
Most items I just copied over from the old issue, and I readjusted the numbers to fit with the PDF I had (which I thought was the most recent, but maybe I was wrong). I think the item about fig. 13 probably refers to the figure being too long - removing `Acnt` fixes that (it may still be a little too long, but at least it doesn't overlap with the page number anymore).

Ideally, I'd move `Acnt` to some place where we actually use it. I wouldn't mind it being next to the definition of `NewEpochState`.

**Comment by williamdemeo** [comment]
We need to clarify the item "Fig 13 format."

**Comment by williamdemeo** [comment]
> Ideally, I'd move `Acnt` to some place where we actually use it. I wouldn't mind it being next to the definition of `NewEpochState`.

@WhatisRT `Acnt` was moved into the hidden code block just above where it previously stood.  This was done in the (merged) PR #292, where I added the following explanation to the text of the PDF (so that hiding the definition doesn't confuse the reader):

"The \AgdaRecord{Acnt} record has two fields, \AgdaField{treasury} and \AgdaField{reserves}, so the \AgdaBound{acnt} field in \AgdaRecord{NewEpochState} keeps track of the total assets that remain in treasury and reserves."

**Comment by williamdemeo** [comment]
I worked on refactoring the `NEWEPOCH` proof in an effort to make it more readable.  In particular, I tried removing the huge `let` binding, introducing all the assignments as proper definitions.  Unfortunately, this broke many things that I wasn't able to fix... yet.  I'll try again with a slightly less dramatic refactoring.
