### ISSUE TITLE
`⇀` may benefit from a rename

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#325]
I like this notation, but the issue is that it can be accidentally mixed up with the regular function arrow. It would have been nice to force parentheses around the operator, but this appears to be impossible. We could rename it to something like `（_⇀_）`, but that may be too heavy.

**Comment by WhatisRT** [comment]
We decided to see if we can rebind `⇀` on the LaTeX side to a version of it that's easier distinguished from the function arrow. However, if that breaks alignments it's probably not worth it and we can just give up.

**Comment by williamdemeo** [comment]
Imho, renaming or reformatting `⇀` is totally unnecessary.  The harpoon symbol is standard notation for a partial function... and we are lucky Agda supports it 🐔❤️

**Comment by WhatisRT** [comment]
Yes, but we do have customers. And if they tell us that this is hard to read, we should at least try to solve their problem. Just because we know what to look out for doesn't mean everyone does. So please look at least for some options, post what you found here and who knows, maybe there'll be a version of `⇀` that's a little more obviously different from `→`. And if there isn't that's fine, but then we can at least tell the next person that finds them hard to distinguish that we tried (and show them what options there are).
