### ISSUE TITLE
Prove that GA deposits match current proposals

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#367]
We should prove that the following property is an invariant, i.e. that if it holds for some state it also holds when we successfully apply a block to that state.

```agda
filterˢ isGADeposit (dom (UTxOState.deposits utxoSt))
    ≡ fromList (map (λ where (id , _) → GovActionDeposit id) govSt)
```

Where `isGADeposit` is a decision procedure whether a deposit was constructed via the `GovActionDeposit` constructor.

**Comment by jmchapman** [comment]
This involves the utxo rule and the gov rule so the proof should live at the level of the ledger rule.

**Comment by jmchapman** [comment]
check what the right notion of the equality is above

**Comment by jmchapman** [comment]
Step 1 should be to encode the statement in Agda and check it makes sense.
