### ISSUE TITLE
document: Missing details regarding removal of pointer address support

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#406]
Please document the changes coming regarding the pointer addresses in Conway era. Missing in the ledger specification

**Comment by WhatisRT** [comment]
It's technically not missing - we're only removing things. All we could do would be to add some prose describing what we're removing.

**Comment by ashisherc** [comment]
yes, every such change must be documented as we have a ref node implementation and for us the source of truth is the ledger spec pdf.
