### ISSUE TITLE
Ratify governance actions in the correct order

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#427]
We are currently ratifying the governance actions in order in which they were submitted, but this is only the secondary order. First, we need to sort them by their type.

The order is:
1. Motion of no-confidence
2. New committee/threshold
3. Update to the Constitution or proposal policy
4. Hard Fork initiation
5. Protocol parameter changes
6. Treasury withdrawals
7. Info

**Comment by williamdemeo** [comment]
List of governance actions should be rearranged as follows: group by the [constructors](https://github.com/IntersectMBO/formal-ledger-specifications/blob/master/src/Ledger/GovernanceActions.lagda#L59C1-L66C1), where order of the groups is as in the descriptions above.  Within each group, the order should be the submission order.

**Comment by WhatisRT** [comment]
There are actually two places where this rearrangement could happen:
- when `EPOCH` calls `RATIFY`, or
- when `GOV` adds a new proposal to the state.

The second option means the 'sortedness' is an invariant, so maybe that's a bit cleaner.
