### ISSUE TITLE
GHC panic

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#434]
When updating nixpkgs & Agda, I got the following error:

```
<no location info>: error:
    panic! (the 'impossible' happened)
  GHC version 9.6.5:
        coreToStgArgs
  ((scc<du_isDecEquivalence_398> v0_s5GuW)
   `cast` (Sub (Sym Univ(nominal CorePrep
                         :: Any, Any -> Any -> T_Dec_20))
           :: (Any -> Any -> T_Dec_20) ~R# Any))
  `cast` (SelCo:Fun(arg)
              (Sub Univ(nominal CorePrep
                        :: Any -> Any, (Any -> Any -> T_Dec_20) -> T_IsDecEquivalence_44))
          :: Any ~R# (Any -> Any -> T_Dec_20))
  v0_s5GuW
  v0_s5GuW
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:189:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/CoreToStg.hs:605:17 in ghc:GHC.CoreToStg
  CallStack (from HasCallStack):
    panic, called at compiler/GHC/Utils/Error.hs:454:29 in ghc:GHC.Utils.Error
```

It was this commit: https://github.com/IntersectMBO/formal-ledger-specifications/pull/432/commits/45e66c2e50e18823512539c10cb0171cf44a04f7

If this bug isn't known, we should see if it is also there for different GHC/Agda versions. Then, if the versions are interesting enough, we can try to minimize it.

**Comment by WhatisRT** [comment]
I did some minimizing here: https://github.com/IntersectMBO/formal-ledger-specifications/tree/andre/investigate-ghc-bug

Current steps to reproduce:
```
nix-shell -A ledger.hsExe --command "unpackPhase; cd Ledger; cabal build --enable-profiling"
```

**Comment by doyougnu** [comment]
This looks related to https://gitlab.haskell.org/ghc/ghc/-/issues/24718

**Comment by WhatisRT** [comment]
Thank you, looks to me like that would be this issue most likely. I'm closing this for now, we can reopen it if it turns out this is a different bug.
