### ISSUE TITLE
Remove add `field` and `constructor` keywords from the PDF

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#441]
- `field` is simply confusing to people not familiar with Agda. It
  adds nothing, because we don't have any entries which aren't fields
  (at least not in what we show in the PDF).

- `constructor` will mostly be obsoleted by #373. We may use it in the
  future for things other than states and environments (but we
  probably won't), in which case we could show those `constructor`
  declarations.

**Comment by williamdemeo** [comment]
> * `field` is simply confusing to people not familiar with Agda. It
>   adds nothing, because we don't have any entries which aren't fields
>   (at least not in what we show in the PDF).

This isn't true. (See counterexamples below.)  However, I'm not saying we shouldn't hide the `field` keyword, and I'll go ahead and make a PR with the proposed changes.  I just wanted to make sure you were aware that the field keyword is serving a purpose, albeit a very small one, in a couple of places.

In `Ledger.Introduction`:
```agda
record Computational (_⊢_⇀⦇_,X⦈_ : C → S → Sig → S → Set) : Set where
  field
    compute     : C → S → Sig → Maybe S
    ≡-just⇔STS  : compute Γ s b ≡ just s' ⇔ Γ ⊢ s ⇀⦇ b ,X⦈ s'

  nothing⇒∀¬STS : compute Γ s b ≡ nothing → ∀ s' → ¬ Γ ⊢ s ⇀⦇ b ,X⦈ s'
```

In `Ledger.TokenAlgebra`:
```agda
record TokenAlgebra : Set₁ where
  field  Value : Set
         ⦃ Value-IsCommutativeMonoid' ⦄ : IsCommutativeMonoid' 0ℓ 0ℓ Value

  MemoryEstimate : Set
  MemoryEstimate = ℕ
```

**Comment by WhatisRT** [comment]
Yes, but for `TokenAlgebra` there is actually no reason to have this be part of the record (i.e. I'd prefer it to be outside). For `Computational` it does make sense from an Agdaists perspective, but I prefer changing the PDF over keeping the `field` keyword. It doesn't really add anything to the PDF in that case either.
