### ISSUE TITLE
What to do about `Set` in the PDF?

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#444]
`Set` is confusing to people not familiar to Agda/type theory. Here are some options:
- rename/display it as `Prop` (or even use the actual `Prop`?) or `Type` (probably as confusing as `Set`)
- use something like `Rel`
- others?

**Comment by WhatisRT** [comment]
We agreed that we'd rename `Set` to `Type` everywhere, and add a very short explanation for 'propositions as types'. If this is still confusing to people, we can try `Proposition` as an alias for `Type`.

**Comment by jmchapman** [comment]
I would avoid renaming Set to Type and also not then capturing the name Set. 

I think this is from Bengt's book.

I wise man once said "Set is Agda's name for Type" <- you can write this in the document.

**Comment by WhatisRT** [comment]
There are two reasons why `Set` is bad in our case:
- it is confusing to people who don't know Agda (why does `actionWellFormed` return a `Set`?)
- we also have 'actual' sets, which are different from `Set`.

Anything that people will understand without explanation is better than something that does need an explanation, that why I personally prefer `Prop` (or `Proposition`), but Ulf and William convinced me to go with `Type`. That does need an explanation, but is at least less confusing than `Set`.

**Comment by williamdemeo** [comment]
I'll go with the consensus we arrived at on Tuesday (change Agda's Set to Type).  We can revert if this makes @jmchapman very unhappy 😰 ...an alternative would be to find a new notation for @WhatisRT's Set.  Perhaps, `aSet` or `AkSet`?  The latter stands for "Andre Knispel Set" or "Also known as Set" (depending on the context).

**Comment by jmchapman** [comment]
or `set`, `SET`,`ZSet`, `ZFSet`, `ZFCSet`. Although if it only appears for predicates and relations I'm coming around to Andre's notion of `Prop` :)

**Comment by jmchapman** [comment]
I think the Agda terminology comes from here:

https://www.cse.chalmers.se/research/group/logic/book/book.pdf

**Comment by WhatisRT** [comment]
Naming our axiomatic sets `Set` and types `Type` is clearly the least confusing option out of these for non-Agda people. This could make it a little more confusing to Agda people reading our specs, but most of our readers know little to no Agda. And I think most Agda people are very receptive to renaming `Set` to `Type` (since many of them do it as well).

**Comment by williamdemeo** [comment]
> I think the Agda terminology comes from here:
> 
> https://www.cse.chalmers.se/research/group/logic/book/book.pdf
> 
> Or possibly Martin-Löf

Chapter 19, "Types," in the book by NPS, explains how to represent the theory of sets in the theory of types.  It is a nice explanation, but it's not clear to me that this is where the use of `Set` instead of `Type` in Agda comes from.  Though something tells me that if I reread that chapter a few times and let it sink in for a while, then it might become obvious that this is precisely where it comes from! 😅
