### ISSUE TITLE
Naming of `mapPartial`

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#446]
`mapPartial` isn't a a name that will be understood without explanation. Should we rename it to something else? Are there other good options, like a set-builder notation?

**Comment by WhatisRT** [comment]
We discussed some alternative options like `map*`, `map?` and `mapPartialFun`. Classical notation for mapping a set with a function would be `f(X)` or `f[X]` where `X` is a set, but that doesn't really apply here.

For now, we decided to leave it as it is and add a description for `mapPartial` in the `Notation` Section.

**Comment by jmchapman** [comment]
`mapMaybe`?

**Comment by WhatisRT** [comment]
I guess that's another option, but it doesn't save us from having to explain it. In which case, sticking with `mapPartial` is a bit easier.

**Comment by jmchapman** [comment]
It still requires explanation but it's Haskell terminology so should be more familiar to some...
