### ISSUE TITLE
document: is the stake key deposit counted towards staked ADA?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#451]
With the new introduction of govActionDeposit, deposited when a gov action is submitted, this deposit is counted towards the staked ADA and towards voting power of this stake key.

Similarly, is the stake key registration deposit counted towards the staked ADA for this rewards address to not lose potential staking rewards?

**Comment by WhatisRT** [comment]
No, governance action deposits are the only deposits that count towards the stake distribution. The other deposits have never been included in the stake distribution and we're not changing that.

**Comment by ashisherc** [comment]
@WhatisRT does the gov action deposit count towards staked ADA for staking rewards? or just towards voting power?

**Comment by ashisherc** [comment]
@WhatisRT

**Comment by WhatisRT** [comment]
It's just for voting power. Staking rewards need to be given up in order to propose.

**Comment by ashisherc** [comment]
ledger Spec section 4.2, page 11 reads - `While the deposit is held, it is added to the deposit pot, similar to stake key deposits. It is also counted towards the stake of the reward address to which it will be returned, so as not to
reduce the submitter’s voting power when voting on their own (and competing) actions.`

If the deposit is counted towards stake of the reward address, it means it will also earn staking rewards, contrary to your previous comment.

@WhatisRT can you please keep this issue open until documented in detail.

**Comment by ashisherc** [comment]
+ Figure 37 defines that the stake key deposit is NOT counted towards the stake of the rewards address

**Comment by WhatisRT** [comment]
> ledger Spec section 4.2, page 11 reads - `While the deposit is held, it is added to the deposit pot, similar to stake key deposits. It is also counted towards the stake of the reward address to which it will be returned, so as not to reduce the submitter’s voting power when voting on their own (and competing) actions.`
> 
> If the deposit is counted towards stake of the reward address, it means it will also earn staking rewards, contrary to your previous comment.

Ah, I believe that paragraph was copied over from the CIP without the necessary adjustments.

> * Figure 37 defines that the stake key deposit is NOT counted towards the stake of the rewards address
> 
> I'm not sure if that's the same value used for rewards calculation, pool stake, and if the stake reg deposit is entirely omitted from both as it is currently.

Note that this spec gives only the figures for things that actually change wrt. the previous eras. Reward calculation is entirely unaffected, and the only change to the block production stake is that pointer addresses are omitted in `mkStakeDistrs`.
