### ISSUE TITLE
document: how are the existing stake key deposits are tracked?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#452]
With the new Conway spec, there is an introduction to specifying a stake key deposit (earlier a fixed amount) for registering a stake key.

I assume, this amount is tracked per stake address and is returned when the stake key is de-registered. 

Please document what happens to the existing stake key deposits. Is the ledger now tracking every existing stake address deposit as 2 ADA (the previous default)? This could be documented together with https://github.com/IntersectMBO/formal-ledger-specifications/issues/451 as both are related.

**Comment by WhatisRT** [comment]
Note that you cannot just put in whatever deposit you like, it still needs to be the exact amount specified in the protocol parameter.

And yes, the map will be populated with the existing deposits as part of the era transition.
