### ISSUE TITLE
doc: double voting power when delegated to spo + drep?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#465]
when a stake cred is delegated to spo and then also delegates to a dRep, is the voting power counted towards both representatives?

**Comment by WhatisRT** [comment]
Yes. I wouldn't view it as "double", it's rather done in a way that's not detrimental to security: you can participate in both systems at the same time. For security in consensus high participation is crucial, so giving people reasons not to participate is a terrible idea.

**Comment by ashisherc** [comment]
okay. can this plz be documented in the spec?
