### ISSUE TITLE
idea? - simplify gov_action_id

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#470]
For better efficiency and tooling support, it would be great if gov action id can be a simple hash. Having a unique identifier for a gov action will make it easy to ref and share gov actions across the community.

**concatenate txid and index**
The simplest option is to just concatenate the transaction_id and gov_action_index,

gov_action_id = 34 bytes

`gov_action_id = [ transaction_id | gov_action_index ]`

eg. _91d5b6a83ab7062009dbf3c23802126eac1445df16e6f312eae16fc15c6095b6_**7**

since the tx_id is always hash32, it is easier to break it down to the current form for referencing. 

This kind of implementation has been used previously for pointer addresses.

**Comment by WhatisRT** [comment]
Note that `TxIn` is also a pair of `TxId` and index, so this is not a new concept. So I'm not sure why this should be better for tooling. Applying an additional hash function will also make validation of every vote a bit more expensive, so I'd argue that it's actually less efficient.

For communication, I'd just concatenate the index in hex form to the txid. That means there'd be a variable-length identifier, but it's very easy to find the transaction that made the proposal. Alternatively it could be padded with some zeros for fixed-length.

In any case, it's probably too late to make such a change anyway. There'd have to be very good reasons to convince people to potentially delay the release.
