### ISSUE TITLE
fixed-output derivation sha is wrong for agda-stdlib-classes

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/formal-ledger-specifications#473]
I believe the FOD sha for agda-stdlib-classes listed at version 2.0 is in fact

```
sha256-PcieRRnctjCzFCi+gUYAgyIAicMOAZPl8Sw35fZdt0E=
```

When using this sha, we hit an error trying to use formal-ledger as a library with classes as a transitive dependency:

https://github.com/cardano-scaling/hydra-formal-specification/actions/runs/9569876114/job/26383379883#step:5:10300

**Comment by WhatisRT** [comment]
Nix's 'if you have that hash in your store, I'm not even going to ask any questions' feature strikes again!

**Comment by locallycompact** [comment]
https://github.com/IntersectMBO/formal-ledger-specifications/pull/476
