### ISSUE TITLE
document: new/update committee specs

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/formal-ledger-specifications#477]
1 - there is an irregularity between the ledger spec and CDDL regarding the new committee gov action naming, CDDL specifies `update_committee` while the ledger spec refers to it as `NewCommittee`

2 - please document details regarding creating and updating committee members,

`update_committee = (4, gov_action_id / null, set<committee_cold_credential>, { committee_cold_credential => epoch_no }, unit_interval)`

- How can a new committee be created to replace the previous one? How can a committee be updated?
- What happens when the cold_credential set is empty? but cold_cred->epoch map has data.
- Can cold_credential -> epoch map be empty?
- Can a committee member be removed? How? (not resign)

Specifics of `update_committee` gov action will be constructive.

**Comment by WhatisRT** [comment]
1. We need to decide what the name should be, I'll talk to the relevant people about that.
2. Note that there's an explanation for `NewCommittee` in the spec:
    > changes to the members of the constitutional committee and/or to its signature threshold and/or terms
    All the questions questions about details should be answered by looking at `GOV/ENACT/RATIFY`. The first map adds members with an expiration epoch, the second one removes members and nothing special happens if any of those are empty.

**Comment by ashisherc** [comment]
>     The first map adds members with an expiration epoch, the second one removes members and nothing special happens if any of those are empty.

@WhatisRT  I think you mean first set to remove members and second map to add members with expiry. Could this please be documented in the ledger spec.

**Comment by WhatisRT** [comment]
I don't know why the CDDL has the arguments in another order, but I was referring to the arguments in the order they appear in the spec.

**Comment by ashisherc** [comment]
@WhatisRT might require the change of order in the spec, CDDL order seems correct (afaik)
