### ISSUE TITLE
PDF improvement: capitalization convention for section headings

### ISSUE THREAD

**Issue by williamdemeo** [IntersectMBO/formal-ledger-specifications#479]
Currently, all but the 9th section of the Conway spec follow the convention of using sentence-style capitalization for all section headings.  We should decide whether to (a) stick with that convention and fix the capitalization of Sec 9 (and Appendix C) or (b) convert the document to the other standard convention, which is to capitalize all "major" words in a section heading.

(If we go with option (a), then Appendix C should be changed from "Bootstrapping the Governance System" to "Bootstrapping the governance system" for example.)

**Comment by williamdemeo** [comment]
The following could also fit into this issue:

- [ ] [Line 1](https://github.com/IntersectMBO/formal-ledger-specifications/blob/52e31136cdfb6e38130cacaed75392fece71c0a2/src/Ledger/EssentialAgda.lagda#L1) of `EssentialAgda.lagda`: The section name "Appendix: Agda essentials" should be "Agda essentials" or "Agda Essentials," depending on the capitalization convention we adopt.  In either case, the word "Appendix" should be removed from the section heading (though we might want to add a heading at the top of the first page of the appendix that says "Appendix").

**Comment by WhatisRT** [comment]
I have no real preference with this, other than to appeal to precedent. The Shelley spec and all specs past that use title case for every (sub)section heading, and I see no reason to change that.

**Comment by williamdemeo** [comment]
Since past specs use title case for section headings, I'll change the Conway spec to conform with that convention.
