### ISSUE TITLE
PDF improvement: font inconsistencies

### ISSUE THREAD

**Issue by williamdemeo** [IntersectMBO/formal-ledger-specifications#480]
The following inconsistencies in the capitalization of section titles and symbol fonts used in the PDF should be resolved.

- [x] [Lines 198--219](https://github.com/IntersectMBO/formal-ledger-specifications/blob/52e31136cdfb6e38130cacaed75392fece71c0a2/src/Ledger/Introduction.lagda#L198C16-L219C22) of `Introduction.lagda`: The powerset symbol introduced in the Introduction does not denote the actual powerset used later in the document, and it is typeset with the `\AgdaBound{ℙ}` macro in the figure.  In the prose and in figures later in the document, when it denotes the actual powerset from the `Set` module, it's typeset as `\AgdaFunction{ℙ}`.

- [x] [Line 82](https://github.com/IntersectMBO/formal-ledger-specifications/blob/52e31136cdfb6e38130cacaed75392fece71c0a2/src/Ledger/Ratify.lagda#L82) of `Ratify.lagda`: "Each of the $P_x$ and $Q_x$ are protocol parameters."  Using Agda font for P and Q would make it easier to make sense of this sentence and connect these symbols to those appearing in the figure.

(Line numbers mentioned above correspond to [commit 52e3113](https://github.com/IntersectMBO/formal-ledger-specifications/commit/52e31136cdfb6e38130cacaed75392fece71c0a2), but they are likely the same or similar to those of the latest commit.)

**Comment by williamdemeo** [comment]
Apparently, many uses of `ℙ` and `_∈_` do not actually come from the original definitions in the `Set` module (which are Agda fields, typeset in red), but are shadowed by the `IsSet` interface, which define them as functions, typeset in blue.

This is another unfortunate consequence of using fancy type classes.

A quick and dirty fix would be to simply change the color definitions in the `agda.sty` file so that fields and functions are typeset in the same color.

An alternative would be to stop using the `IsSet` interface, but perhaps that type class is buying us a lot of nice simplifications.

**Comment by WhatisRT** [comment]
Not using that typeclass means putting `ˢ` in lots of places, so I don't want to do that. I don't consider just changing the color in the `.sty` file a hack.
