### ISSUE TITLE
`hasParent` needs to match GAs

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#539]
Currently we just throw away everything except the `GovActionID`. Instead, we need to ensure that the parent also has the same type of GA, otherwise `hasParent` should fail.

**Comment by williamdemeo** [comment]
I'm not sure how to make a decidable equality for `GovernanceAction`.  I think this would first require decidable equality of `Map` type, which I believe we don't have yet.  It seems to me, the closest we could get to `DecEq` for `Map` would be a decidable relation, namely, `Decidable _≡ᵐ_`, where, recall, `_≡ᵐ_ : Map A B → Map A B → Type` is defined as `(x , _) ≡ᵐ (y , _) = x ≡ᵉ y`, so we first need `Decidable _≡ᵉ_`.  Even if we have all of this, I'm not sure having `Decidable` "equality" relation on maps suffices in place of `DecEq`.

**Comment by WhatisRT** [comment]
You shouldn't actually compare governance actions for equality, you should just check if they have the same constructor. Except for `NewCommittee` and `NoConfidence`, these need to go into the same bucket.
