### ISSUE TITLE
Align deposit calculations in the Haskell version of the spec with the implementation

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/formal-ledger-specifications#590]
In the implementation we store the deposits inside the DRep/PoolParams data structure. To align the Haskell version of the spec better with the implementation we should get rid of the deposits map and store them in the same way as in the implementation.

**Comment by jmchapman** [comment]
need more detail:
*what is the motivation? Are conformance testing failing?

**Comment by Soupstraw** [comment]
I think this one can be closed, I was running into some trouble when adding conformance tests for the `UTXO` rule, but it turned out that everything that I needed was actually available deep inside the state/env. It would've been easier if the spec and the implementation stored this data in the same place, but I don't think it's that important.
