### ISSUE TITLE
Properly implement `isSigned`

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/formal-ledger-specifications#593]
At the moment it uses a dummy implementation. We need an implementation that actually checks the signature.

**Comment by jmchapman** [comment]
* need more info
* a decision how to implement it
* an estimate

**Comment by TimSheard** [comment]
I think this may be talking about finding witnesses for Keys and Script hashes in a transaction body.
Currently we randomly generate things that look like hashes, but finding the Key or Script that hashes
to that hash is impossible.  We will have to randomly generate an universe of pairs (Map Hash KeyPair, Map Hash Script) and then pick hashes from this universe. Then we can figure out how to sign by using this universe.
Of course I could be wrong.

**Comment by Soupstraw** [comment]
The problem is that in the spec at the moment the signing function always returns `zero` and the `isSigned` check always returns `⊤`. This means that we don't really check any signatures in the spec during conformance testing. 

We should talk about this at a formal ledger meeting since I'm not completely sure how to solve this. We probably need to somehow pass the signing function from the Haskell implementation to the spec.

**Comment by WhatisRT** [comment]
The idea we've had was to parametrize the `Foreign` modules over some kind of crypto dictionary record. This should add this dictionary as an extra argument to the generated `step` functions. Then, on the Haskell side we could wrap these to turn the dictionary into a type class constraint instead and add an instance. At that point there should be no extra overhead to call those functions anymore.
