### ISSUE TITLE
Vertical vectors in LaTeX output

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#7]
Vertical vectors make the PDF way more readable. The issue here is that the LaTeX environment for rendering Agda isn't compatible with that, at least what I tried didn't work.

If we have some way of fixing/working around this issue, the easiest way would be to wrap some marker around the tuples, and then run some preprocessing script, but maybe there are better solutions.

There are two steps:
- [x] Produce a single working example by editing the LaTeX manually.
- [ ] Write some automation that we can hook into the build process.

Integration into CI isn't part of this issue, I can take care of that.

**Comment by williamdemeo** [comment]
@WhatisRT could you point to a good example of where you would want a vertical vector?  I suspect you wanted them in the actual Agda code (probably hard), but maybe you meant you just want vertical vectors in the documentation explaining the code (probably easier).

**Comment by WhatisRT** [comment]
For example `POOL-regpool` in Figure 22. Compare with `Pool-reg` in Figure 25 of the Shelley spec. And yes, I don't expect this to be possible in Agda.

The general idea for this would be to first edit the LaTeX that Agda generates by hand, just to get a single working example. If you get it to work you can put it in a draft PR and once we have that, we can think about how to best automate this.

**Comment by WhatisRT** [comment]
For the paper, @omelkonian introduced `minipage`s to have code blocks next to each other, and in one instance I used them for making a vertical vector. It looks like this:

```agda
⟦ (utxo ∣ txins ᶜ) ∪ˡ outs txb
, updateDeposits pp txb deposits
, fees + txfee
, donations + txdonation ⟧
```

I think that's reasonable, but it would be even nicer if we can instead make one big pair of parentheses around it (and remove the existing brackets and commas).

It's also important to consider the requirements for integrating a LaTeX preprocessor:
- it needs to run as part of the nix/CI setup
- it needs to be maintainable

For maintainability, the most natural languages to write such a tool in would be Haskell or Agda, while for integration, something like bash or python might be easiest (but integrating a Haskell or Agda program also wouldn't be too difficult). If the actual transformation turns out to be really easy, it may be worth considering a `sed` one-liner.

**Comment by williamdemeo** [comment]
Here's a first pass, by manually tinkering with the generated `Deleg.tex` file. 
![firstpass-vert-vecs](https://github.com/IntersectMBO/formal-ledger-specifications/assets/3528228/ba78891d-4362-4f1e-b3b5-69b72f20264e)
 Comments?
